language: java


jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - secure: "CDQR/GwF8QNNhSZ0p52xuEdYjb75SJicSD3NmtQvfoAd1yfK3NbXSRC6OSvHVUhw5R/GLVH7AAYByDJ45uFJo09yCe+rh2H+KOsNDk4edV0lYsOLS+0F9nQbkR5/36KE+vXUN4BDPUknBPufF8uIqta0L4EsGINYd1350VLI7gVI/fHIH+SoMJk0jX45G/hN/R9xjP4sLZdqlX4+OlhAmmHajBAyLjWfM5ngs02xpRZl9QVnj29WrjJ4WK7bmyObgPEzQzUGfCZl2PzYJlKmoj9ic9GCq+0/OOPOv3DMPLAXONXbMO8P1xwUhWZDNqrYDtrA7ojt9gBHa0MxZ9EtxyJh4jc9b2C3o6VYGl47tFkPij1lH30UkaFPCd0ue/5PBpm4mn8BpRBLSjwhNQ57LdQGc9zmswaDavXyDJ1sEcKqvC5cGpJH8IrtXixhJB+IRUCJYE6yWxK8SFk7Eg3w06GcjqZSMEkrDzhhl4Hk4e0ad5ha0u9a2HVuSW2jPZb1Xa3rZ6c3LsSipia2L3A4+ht8EHh2TRd4c+NUr4vCiue5VOCI+0k/ULeq63gpFMwBxzXTQtqEav9kWokKbV2vSnkbcT+TH+WmzUfpxVBTdD3NFqJI+QRDYQB/XsvcjdnQ3Y7Sb3v/jOE9MzEc3wkzTuRxrHCK4qVxCp18192MBlw="

jobs:
  include:
    - stage: build
      install: ./scripts/install.sh
      script:
      - ./scripts/script.sh
